name: Go

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Linting
        uses: golangci/golangci-lint-action@v3.1.0
      - name: Unit tests
        run: make test
      - name: Docker run
        run: make docker-run
